from satellite import Tracker

track = Tracker('Самара', 'NOAA 1')
print(track.getSatCoord())
print(track.getSatAltitude())
print(track.getSatAzimuth())
print(track.getSatInterCode())
print(track.getSatPerigee())
print(track.getSatApogee())
print(track.getSatIncl())
print(track.getSatPeriod())
print(track.getSatSource())
print(track.getSatLaunchSite())
print(track.getSatVisual())
print(track.getSatRadio())
